# Generated by Django 2.0 on 2017-12-07 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uf_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uf',
            name='id',
        ),
        migrations.AlterField(
            model_name='uf',
            name='date',
            field=models.DateField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
